# Generated by Django 4.1.6 on 2023-03-02 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
